version: "2.3"
services:
  noetic:
    image: turtle_sim:latest
    container_name: turtle_sim
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "5000:5000"
    environment:
      - TELEOP_CONTROLLER=${TELEOP_CONTROLLER:-disabled}
      - ENABLE_MANIPULATOR=${ENABLE_MANIPULATOR:-false}
      - MANIPULATOR_GUI=${MANIPULATOR_GUI:-disabled}
      - HEADLESS=${HEADLESS:-true}
    tty: true
    networks:
      - turtlenet
networks:
  turtlenet:
    name: turtlenet
