version: "2.3"
services:
  gzserver:
    container_name: gzserver
    build:
      context: ./
      dockerfile: Dockerfile.gzserver
    ports:
      - "11345"
    tty: true
  gzweb:
    container_name: gzweb
    build:
      context: ./
      dockerfile: Dockerfile.gzweb
    ports:
      - "11345"
      - "8080:8080"
    tty: true
